// DEFAULT SUBJECTS
const defaultSubjects = ["Math", "Physics", "Chemistry"];

// INIT
window.onload = () => {
  defaultSubjects.forEach(s => addSubject(s));
};

// ADD SUBJECT
let count = 0;

function addSubject(name="") {
  count++;

  const row = `
    <tr id="row${count}">
      <td>${count}</td>
      <td><input value="${name}"></td>
      <td><input type="number" value="100"></td>
      <td><input type="number" oninput="calc(${count})"></td>
      <td id="g${count}">--</td>
      <td id="s${count}">--</td>
      <td><button onclick="del(${count})">X</button></td>
    </tr>
  `;

  document.getElementById("subjectsBody").innerHTML += row;
}

// DELETE
function del(id){
  document.getElementById("row"+id).remove();
}

// CALC
function calc(id){
  const row = document.getElementById("row"+id);
  const max = row.children[2].children[0].value;
  const obt = row.children[3].children[0].value;

  const pct = (obt/max)*100;

  let grade="F";
  if(pct>=90) grade="O";
  else if(pct>=75) grade="A";
  else if(pct>=60) grade="B";
  else if(pct>=40) grade="C";

  document.getElementById("g"+id).innerText = grade;
  document.getElementById("s"+id).innerText = pct>=40 ? "Pass":"Fail";
}

// GENERATE REPORT
function generateReport(){

  const name = document.getElementById("studentName").value;
  const roll = document.getElementById("rollNo").value;

  if(!name || !roll){
    alert("Enter required fields");
    return;
  }

  const rows = document.querySelectorAll("#subjectsBody tr");

  let html = `
    <h2>ScoreNest Report Card</h2>
    <p>Name: ${name}</p>
    <p>Roll: ${roll}</p>
    <table border="1" width="100%">
      <tr>
        <th>Subject</th>
        <th>Marks</th>
      </tr>
  `;

  rows.forEach(r=>{
    const sub = r.children[1].children[0].value;
    const marks = r.children[3].children[0].value;

    html += `<tr><td>${sub}</td><td>${marks}</td></tr>`;
  });

  html += `
    </table>
    <p style="margin-top:20px;font-size:12px;">
      Generated by ScoreNest Report Generator
    </p>
  `;

  document.getElementById("reportOutput").innerHTML = html;
}

// PRINT
function printReport(){
  window.print();
}

// NAV
function showSection(id){
  document.querySelectorAll(".section").forEach(s=>s.style.display="none");
  document.getElementById(id).style.display="block";
}

// RESET
function resetAll(){
  location.reload();
}